name: Kouri Daily Check-in (API)

on:
  schedule:
    - cron: "40 16 * * *"   # 北京时间 00:40
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run API check-in
        env:
          KOURI_COOKIE:    ${{ secrets.KOURI_COOKIE }}
          UA:              ${{ secrets.UA }}
          VOAPI_USER:      ${{ secrets.VOAPI_USER }}       # 可选
          ACCEPT_LANGUAGE: ${{ secrets.ACCEPT_LANGUAGE }}  # 可选
          TURNSTILE_TOKEN: ${{ secrets.TURNSTILE_TOKEN }}  # 可选
        run: python kouri_checkin_api.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kouri-api-artifacts
          path: artifacts/**
          if-no-files-found: ignore
